show contents of malformed keyfile, may help clarify some errors
ping #2

diff --git a/travis-encrypt b/travis-encrypt
--- a/travis-encrypt
+++ b/travis-encrypt
@@ -26,18 +26,20 @@ value="$1"
 keyurl="https://api.travis-ci.org/repos/$user/$repo/key"
 echo "Fetching key from $keyurl ..." >&2
 keyfile=$(mktemp)
+keyfile2=$(mktemp)
 curl -s "$keyurl" > "$keyfile" || {
-    echo "Couldn't fetch key from $keyurl!" >&2
+    echo "Couldn't fetch key from $keyurl!"
     exit 1
-}
+} >&2
 
 # (Exceptionally poor)-man's JSON-to-PEM
 # Some Travis-CI pubkeys have " RSA PUBLIC KEY", where others have the standard " PUBLIC KEY".
-sed -i 's|\\n|\n|g; s|"|\n|g; s/ RSA PUBLIC KEY/ PUBLIC KEY/g' "$keyfile"
-grep -q "BEGIN PUBLIC KEY" "$keyfile" || {
-    echo "Key file from $keyurl seems malformed: $keyfile" >&2
+sed 's|\\n|\n|g; s|"|\n|g; s/ RSA PUBLIC KEY/ PUBLIC KEY/g' "$keyfile" > "$keyfile2"
+grep -q "BEGIN PUBLIC KEY" "$keyfile2" || {
+    echo "Key file from $keyurl seems malformed: $keyfile"
+    echo -e "\t$(cat $keyfile)"
     exit 1
-}
+} >&2
 
 if [[ -z "$value" ]]; then
     read -p "Value to encrypt? " value
@@ -46,8 +48,8 @@ fi
 echo "Encrypting with openssl rsautl ..." >&2
 
 set -o pipefail
-echo -n "$value" | openssl rsautl -encrypt -inkey "$keyfile" -pubin -pkcs | base64 -w0 || {
-    echo "Error in openssl rsautl." >&2
+echo -n "$value" | openssl rsautl -encrypt -inkey "$keyfile2" -pubin -pkcs | base64 -w0 || {
+    echo "Error in openssl rsautl."
     exit 1
-}
+} >&2
 echo $'\nSuccess.' >&2
